import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { axiosInstance } from '../utils/axios';
import Link from "next/link"
export default function Home() {
  const [keyword, setKeyword] = useState("");
  const [posts, setPosts] = useState(null);
  const handleChangeKeyword = (e) => {
    setKeyword(e.target.value)
  }
  const handleSearch = async () => {
    try {
      let fetchedPosts = await axiosInstance.get(`/posts`, {
        params: {
          s: keyword
        }
      })
      console.log('fetchedPosts', fetchedPosts)

      if (fetchedPosts) setPosts(fetchedPosts.data)
      else setPosts([])
    } catch (error) {
      console.log("error", error.message)
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Luan Nguyen Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Luan Nguyen Website
        </h1>
        <div>
          <input type="text" onChange={(e) => handleChangeKeyword(e)}></input>
          <button onClick={() => handleSearch()}>Search</button>
        </div>
        <ul>
          {posts &&
            posts?.map((post) => (
              <li>
                <Link href={`posts/${post?.id}`}>
                  <a>
                    {post?.title}
                  </a>
                </Link>
              </li>
            ))
          }
        </ul>


      </main>


    </div>
  )
}
