name: deploy to aws
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy.sh on server
        uses: fifsky/ssh-action@master
        with:
          command:  |
            cd /training-aws
            ls -a
          host: ${{ secrets.SERVER_DEV_IP }}
          user: ${{ secrets.SERVER_DEV_USER }}
          key: ${{ secrets.SSH_DEV_PRIVATE_KEY}}
          args: "-tt -vvv"